package _ErrorClub.example.demo.audit.enums;

public enum AuditEvento {

    AUTH_LOGIN_SUCCESS,
    AUTH_LOGIN_FAIL,
    AUTH_REFRESH_SUCCESS,
    AUTH_REFRESH_FAIL,

    SOLICITACAO_CRIADA,
    SOLICITACAO_CRIAR_FAIL,
    SOLICITACAO_LISTADA_MINHAS,
    SOLICITACAO_LISTADA_TODAS,
    SOLICITACAO_STATUS_ALTERADO,
    SOLICITACAO_STATUS_FAIL,

    TESTE_LOG
}
