spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5433/easyschool
spring.datasource.username=postgres
spring.datasource.password=0000
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=Ao/ERak+BF46KCdhwMWf5fkwK/hmjZAbYXGFGfKJKjg=
jwt.access-token-expiration=900000