spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/easyschool
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=EasySchool-jwt-secret-key-aaaaaa-aa-aaaaaaaa-aaaa-aaaaa-256-bits!
jwt.access-token-expiration=900000